name: Go
on: 
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: cd remote_write/bin && git clone https://github.com/open-telemetry/opentelemetry-collector.git &&
        cd opentelemetry-collector && make build-binary-internal && cd bin && mv otelcol_darwin_amd64 ../../ &&
        cd ../../ && rm -rf opentelemetry-collector &&
        cd .. && go test --tags=compliance -run "TestRemoteWrite/otel/.+" -v ./
